name: cineslide
description: Devpost Flutter Sliding Puzzle Competition Entry
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  archive: ^3.2.1
  bloc: ^8.0.3
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^1.20.0
  gap: ^2.0.0
  google_fonts: ^2.2.0
  image: ^3.1.3
  intl: ^0.17.0
  just_audio: ^0.9.18
  modal_bottom_sheet: ^2.0.0
  photofilters: ^3.0.1
  rive: ^0.8.1
  carousel_slider: ^4.0.0
  themed: ^3.0.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.18
  visibility_detector: ^0.2.2

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/
    - assets/images/dashatar/gallery/
    - assets/images/dashatar/success/
    - assets/images/dashatar/green/
    - assets/images/dashatar/blue/
    - assets/images/dashatar/yellow/
    - assets/images/muybridge/
    - assets/scenes/
    - assets/rive/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SourceCodePro-Black.ttf
          weight: 900
          